export const CATALOGUE_GROCERIES_REQUEST = 'CATALOGUE_GROCERIES_REQUEST';
export const CATALOGUE_GROCERIES_SUCCESS = 'CATALOGUE_GROCERIES_SUCCESS';
export const CATALOGUE_GROCERIES_FAIL = 'CATALOGUE_GROCERIES_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';