export const ADD_TO_SHOPPING_LIST = 'ADD_TO_SHOPPING_LIST';
export const REMOVE_FROM_SHOPPING_LIST = 'REMOVE_FROM_SHOPPING_LIST';
export const CLEAR_SHOPPING_LIST = 'CLEAR_SHOPPING_LIST';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';